<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="microservices" nsURI="http://cloud.microservices" nsPrefix="cloud">
  <eClassifiers xsi:type="ecore:EClass" name="Microservice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" upperBound="-1"
        eType="#//Connection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" upperBound="-1"
        eType="#//Connection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imagePort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ConnectionType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConnectionType">
    <eLiterals name="INTERNAL"/>
    <eLiterals name="OUTPUT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Infrastructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//Microservice" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
